###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "maria cruz",
    "age": 40,
    "email": "maria@gmail.com"
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/64fab55bac91ce0bb90fbc21 HTTP/1.1

###
PUT http://localhost:3000/api/users/64fab55bac91ce0bb90fbc21 HTTP/1.1
Content-Type: application/json

{
    "name": "maria cruz canales",
    "age": "25",
    "email": "ejemplo@gmail"
}

###
DELETE http://localhost:3000/api/users/64fab55bac91ce0bb90fbc21 HTTP/1.1

### crear una nueva categoria 
POST http://localhost:3000/api/category HTTP/1.1
Content-Type: application/json

{
    "name": "automotriz",
    "description": "articulos para vehiculos"
}

### leer todos los categorias 
GET http://localhost:3000/api/category HTTP/1.1

### leer una sola categoria 
GET http://localhost:3000/api/category/jardineria HTTP/1.1

### editar una categoria 
PUT http://localhost:3000/api/category/jardineria HTTP/1.1
Content-Type: application/json

{
    "newname": "ferreteria",
    "description": "articulos varios" 
}

### eliminar categoria 
DELETE http://localhost:3000/api/category/ferreteria HTTP/1.1

### crear un producto 
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

{
    "name": "laptop lenovo",
    "price": 20000,
    "description": "laptop lenovo de uso optimas condiciones",
    "category": "computacion"
}

###leer todos los productos 
GET http://localhost:3000/api/products HTTP/1.1

### leer un solo producto por nombre 
GET http://localhost:3000/api/products/falda HTTP/1.1